# 추상화 수준에 맞는 예외를 던져라

우리가 블랙잭 구현을 너무나도 잘 완료해서 다음과 같은 API를 만들었다고 하자.

```java
public interface BlackjackGame {
    void play();
}
```

게임을 시작하고 베팅금액을 입력했는데 갑자기 다음과 같은 오류 메시지가 뜨며 게임이 종료되어 버렸다.

```text
Exception in thread "main" java.lang.NumberFormatException: For input string: "천원"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at Main.main(Main.java:3)
```


땀이 줄줄 나기 시작한다. 나는 그냥 블랙잭을 하고 싶었는데, 무슨 이상한 오류가 뜬다.
솔직히 하고 싶지 않다. UX가 꽝이다. 그냥 다른 블랙잭을 하러 떠난다...

## 왜 이런 상황이 발생하는가?

기능이 적절히 추상화되어야 하듯, 예외 역시 적절히 추상화되어야 한다.
`BlackjackGame` 이라는 최상위 추상화 계층에서는 저렇게 자세하고도 상세한 예외가 필요없다.
우리는 차라리 다음과 같은 메시지를 보기를 원한다.

```text
애플리케이션 문제로 인하여 블랙잭 게임을 종료합니다.
```

## 어떻게 수행할 수 있는가?

### 예외 번역

하위 계층 예외를 상위 계층 예외로 번역하는 작업을 통해 이를 수행할 수 있다.

```java
public class BlackjackGameImpl {

    public void run() {
        try {
            // 게임 실행 로직
        } catch (Exception e) {
            throw new BlackjackGameException();
        }
    }
}
```

이러면 상위 계층에서는 적절히 추상화된 예외를 받아볼 수 있다.

### 예외 연쇄

> 애플리케이션 문제로 인하여 블랙잭 게임을 종료합니다.

사실 위 예외 메시지는 좀 불친절하게 느껴진다.
나는 다시 하고 싶은데, 뭐가 잘못되었는지도 모르겠고 또 종료될 것만 같다.
이럴 경우에는 예외를 추상화하되, 기존 예외를 같이 껴넣을 수 있다.

```java
public class BlackjackGameImpl {

    public void run() {
        try {
            // 게임 실행 로직
        } catch (Exception e) {
            throw new BlackjackGameException(e);
        }
    }
}
```

이렇게 하면 상위 계층에서는 추상화된 예외와, 상세한 내부 예외까지 모두 확인해볼 수 있다.

```text
Exception in thread "main" java.lang.IllegalStateException: 애플리케이션 문제로 인하여 블랙잭 게임을 종료합니다.
	at Main.main(Main.java:6)
Caused by: java.lang.NumberFormatException: For input string: "천원"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:778)
	at Main.main(Main.java:4)
```
